<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>d8052318-6d07-439f-ba27-8191f78b05ab</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.1.0" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.1.0" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BikeRental.Api.Host\BikeRental.Api.Host.csproj" />
    <ProjectReference Include="..\BikeRental.Generator.RabbitMq.Host\BikeRental.Generator.RabbitMq.Host.csproj" />
  </ItemGroup>

</Project>
