// <auto-generated />
using System;
using BikeRental.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeRental.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(BikeRentalDbContext))]
    [Migration("20251216125148_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BikeRental.Domain.Bicycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Bicycles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red",
                            ModelId = 1,
                            SerialNumber = "SN1001"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Blue",
                            ModelId = 2,
                            SerialNumber = "SN1002"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Green",
                            ModelId = 3,
                            SerialNumber = "SN1003"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Yellow",
                            ModelId = 4,
                            SerialNumber = "SN1004"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Black",
                            ModelId = 5,
                            SerialNumber = "SN1005"
                        },
                        new
                        {
                            Id = 6,
                            Color = "Silver",
                            ModelId = 6,
                            SerialNumber = "SN1006"
                        },
                        new
                        {
                            Id = 7,
                            Color = "White",
                            ModelId = 7,
                            SerialNumber = "SN1007"
                        },
                        new
                        {
                            Id = 8,
                            Color = "Gray",
                            ModelId = 8,
                            SerialNumber = "SN1008"
                        },
                        new
                        {
                            Id = 9,
                            Color = "Orange",
                            ModelId = 9,
                            SerialNumber = "SN1009"
                        },
                        new
                        {
                            Id = 10,
                            Color = "Blue",
                            ModelId = 10,
                            SerialNumber = "SN1010"
                        },
                        new
                        {
                            Id = 11,
                            Color = "Purple",
                            ModelId = 1,
                            SerialNumber = "SN1011"
                        },
                        new
                        {
                            Id = 12,
                            Color = "Brown",
                            ModelId = 3,
                            SerialNumber = "SN1012"
                        });
                });

            modelBuilder.Entity("BikeRental.Domain.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Brakes")
                        .HasColumnType("int");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<double>("WheelSize")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Models", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brakes = 0,
                            MaxWeight = 120.0,
                            Name = "Stels Navigator",
                            PricePerHour = 150m,
                            Type = 0,
                            Weight = 15.0,
                            WheelSize = 26.0,
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Brakes = 1,
                            MaxWeight = 100.0,
                            Name = "Cube Race",
                            PricePerHour = 250m,
                            Type = 3,
                            Weight = 12.0,
                            WheelSize = 28.0,
                            Year = 2021
                        },
                        new
                        {
                            Id = 3,
                            Brakes = 0,
                            MaxWeight = 110.0,
                            Name = "Merida Speed",
                            PricePerHour = 300m,
                            Type = 3,
                            Weight = 13.0,
                            WheelSize = 29.0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 4,
                            Brakes = 1,
                            MaxWeight = 50.0,
                            Name = "Forward Junior",
                            PricePerHour = 100m,
                            Type = 4,
                            Weight = 8.0,
                            WheelSize = 20.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 5,
                            Brakes = 0,
                            MaxWeight = 130.0,
                            Name = "Trek FX",
                            PricePerHour = 200m,
                            Type = 0,
                            Weight = 14.0,
                            WheelSize = 27.5,
                            Year = 2022
                        },
                        new
                        {
                            Id = 6,
                            Brakes = 0,
                            MaxWeight = 120.0,
                            Name = "Giant Sport",
                            PricePerHour = 280m,
                            Type = 3,
                            Weight = 14.0,
                            WheelSize = 29.0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 7,
                            Brakes = 0,
                            MaxWeight = 110.0,
                            Name = "Stark Cobra",
                            PricePerHour = 220m,
                            Type = 1,
                            Weight = 13.0,
                            WheelSize = 27.5,
                            Year = 2022
                        },
                        new
                        {
                            Id = 8,
                            Brakes = 1,
                            MaxWeight = 100.0,
                            Name = "Scott City",
                            PricePerHour = 180m,
                            Type = 0,
                            Weight = 12.0,
                            WheelSize = 28.0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 9,
                            Brakes = 0,
                            MaxWeight = 115.0,
                            Name = "Author MTB",
                            PricePerHour = 260m,
                            Type = 1,
                            Weight = 14.0,
                            WheelSize = 29.0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 10,
                            Brakes = 0,
                            MaxWeight = 100.0,
                            Name = "Orbea Aero",
                            PricePerHour = 320m,
                            Type = 3,
                            Weight = 11.0,
                            WheelSize = 28.0,
                            Year = 2023
                        });
                });

            modelBuilder.Entity("BikeRental.Domain.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BicycleId")
                        .HasColumnType("int");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<int>("RenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BicycleId");

                    b.HasIndex("RenterId");

                    b.ToTable("Rentals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BicycleId = 1,
                            DurationHours = 3,
                            RenterId = 1,
                            StartTime = new DateTime(2025, 12, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BicycleId = 2,
                            DurationHours = 5,
                            RenterId = 2,
                            StartTime = new DateTime(2025, 12, 14, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BicycleId = 3,
                            DurationHours = 2,
                            RenterId = 3,
                            StartTime = new DateTime(2025, 12, 14, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            BicycleId = 4,
                            DurationHours = 6,
                            RenterId = 4,
                            StartTime = new DateTime(2025, 12, 14, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            BicycleId = 5,
                            DurationHours = 4,
                            RenterId = 5,
                            StartTime = new DateTime(2025, 12, 14, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            BicycleId = 6,
                            DurationHours = 7,
                            RenterId = 6,
                            StartTime = new DateTime(2025, 12, 14, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            BicycleId = 7,
                            DurationHours = 5,
                            RenterId = 7,
                            StartTime = new DateTime(2025, 12, 14, 23, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            BicycleId = 8,
                            DurationHours = 3,
                            RenterId = 8,
                            StartTime = new DateTime(2025, 12, 14, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            BicycleId = 9,
                            DurationHours = 4,
                            RenterId = 9,
                            StartTime = new DateTime(2025, 12, 14, 19, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            BicycleId = 10,
                            DurationHours = 6,
                            RenterId = 10,
                            StartTime = new DateTime(2025, 12, 14, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            BicycleId = 2,
                            DurationHours = 3,
                            RenterId = 3,
                            StartTime = new DateTime(2025, 12, 14, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            BicycleId = 3,
                            DurationHours = 4,
                            RenterId = 5,
                            StartTime = new DateTime(2025, 12, 14, 4, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            BicycleId = 6,
                            DurationHours = 2,
                            RenterId = 1,
                            StartTime = new DateTime(2025, 12, 13, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            BicycleId = 8,
                            DurationHours = 5,
                            RenterId = 4,
                            StartTime = new DateTime(2025, 12, 13, 23, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            BicycleId = 10,
                            DurationHours = 3,
                            RenterId = 7,
                            StartTime = new DateTime(2025, 12, 12, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            BicycleId = 1,
                            DurationHours = 2,
                            RenterId = 2,
                            StartTime = new DateTime(2025, 12, 13, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            BicycleId = 5,
                            DurationHours = 6,
                            RenterId = 10,
                            StartTime = new DateTime(2025, 12, 13, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            BicycleId = 4,
                            DurationHours = 7,
                            RenterId = 6,
                            StartTime = new DateTime(2025, 12, 14, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            BicycleId = 9,
                            DurationHours = 5,
                            RenterId = 9,
                            StartTime = new DateTime(2025, 12, 13, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            BicycleId = 7,
                            DurationHours = 3,
                            RenterId = 3,
                            StartTime = new DateTime(2025, 12, 14, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            BicycleId = 6,
                            DurationHours = 6,
                            RenterId = 1,
                            StartTime = new DateTime(2025, 12, 11, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            BicycleId = 3,
                            DurationHours = 4,
                            RenterId = 5,
                            StartTime = new DateTime(2025, 12, 12, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            BicycleId = 8,
                            DurationHours = 2,
                            RenterId = 8,
                            StartTime = new DateTime(2025, 12, 13, 23, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            BicycleId = 2,
                            DurationHours = 5,
                            RenterId = 4,
                            StartTime = new DateTime(2025, 12, 13, 19, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            BicycleId = 9,
                            DurationHours = 7,
                            RenterId = 9,
                            StartTime = new DateTime(2025, 12, 12, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            BicycleId = 1,
                            DurationHours = 2,
                            RenterId = 3,
                            StartTime = new DateTime(2025, 12, 10, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            BicycleId = 6,
                            DurationHours = 5,
                            RenterId = 7,
                            StartTime = new DateTime(2025, 12, 9, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            BicycleId = 10,
                            DurationHours = 3,
                            RenterId = 5,
                            StartTime = new DateTime(2025, 12, 8, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            BicycleId = 3,
                            DurationHours = 4,
                            RenterId = 10,
                            StartTime = new DateTime(2025, 12, 7, 23, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            BicycleId = 7,
                            DurationHours = 6,
                            RenterId = 6,
                            StartTime = new DateTime(2025, 12, 6, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31,
                            BicycleId = 6,
                            DurationHours = 5,
                            RenterId = 4,
                            StartTime = new DateTime(2025, 12, 4, 19, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32,
                            BicycleId = 10,
                            DurationHours = 4,
                            RenterId = 1,
                            StartTime = new DateTime(2025, 12, 2, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 33,
                            BicycleId = 5,
                            DurationHours = 7,
                            RenterId = 9,
                            StartTime = new DateTime(2025, 11, 29, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 34,
                            BicycleId = 7,
                            DurationHours = 5,
                            RenterId = 8,
                            StartTime = new DateTime(2025, 11, 26, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 35,
                            BicycleId = 3,
                            DurationHours = 3,
                            RenterId = 2,
                            StartTime = new DateTime(2025, 11, 24, 21, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BikeRental.Domain.Renter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Renters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "John Smith",
                            Phone = "+1-202-111-22-33"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Mary Johnson",
                            Phone = "+1-202-222-33-44"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Robert Brown",
                            Phone = "+1-202-333-44-55"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Jennifer Davis",
                            Phone = "+1-202-444-55-66"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Michael Miller",
                            Phone = "+1-202-555-66-77"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "William Wilson",
                            Phone = "+1-202-666-77-88"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Elizabeth Moore",
                            Phone = "+1-202-777-88-99"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "David Taylor",
                            Phone = "+1-202-888-99-00"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Linda Anderson",
                            Phone = "+1-202-999-00-11"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "James Thomas",
                            Phone = "+1-202-000-11-22"
                        });
                });

            modelBuilder.Entity("BikeRental.Domain.Bicycle", b =>
                {
                    b.HasOne("BikeRental.Domain.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("BikeRental.Domain.Rental", b =>
                {
                    b.HasOne("BikeRental.Domain.Bicycle", "Bicycle")
                        .WithMany()
                        .HasForeignKey("BicycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeRental.Domain.Renter", "Renter")
                        .WithMany()
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bicycle");

                    b.Navigation("Renter");
                });
#pragma warning restore 612, 618
        }
    }
}
